"""description text

Revision ID: 963738864b4c
Revises: 96ffb83f1260
Create Date: 2021-06-04 16:00:17.578090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '963738864b4c'
down_revision = '96ffb83f1260'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'file', 'user', ['owner'], ['id_user'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'file', type_='foreignkey')
    # ### end Alembic commands ###
