"""second_test mcd fixed

Revision ID: d13cc845f37d
Revises: 963738864b4c
Create Date: 2021-06-08 12:43:46.941239

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd13cc845f37d'
down_revision = '963738864b4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('folder',
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('path', sa.String(length=256), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('description', mysql.LONGTEXT(), nullable=True),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.Column('id_folder', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('parent_folder', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_folder'], ['folder.id_folder'], name='fk_folder_parent'),
    sa.PrimaryKeyConstraint('id_folder')
    )
    op.create_table('space',
    sa.Column('id_space', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('members', sa.JSON(), nullable=True),
    sa.Column('data_shared', sa.JSON(), nullable=True),
    sa.Column('files', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id_space')
    )
    op.create_table('archive',
    sa.Column('id_archive', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('archive_date', sa.DateTime(), nullable=True),
    sa.Column('space_archived', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['space_archived'], ['space.id_space'], name='fk_archive_space'),
    sa.PrimaryKeyConstraint('id_archive')
    )
    op.create_table('file',
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('path', sa.String(length=256), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('description', mysql.LONGTEXT(), nullable=True),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.Column('id_file', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('folder', sa.Integer(), nullable=True),
    sa.Column('owner', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['folder'], ['folder.id_folder'], ),
    sa.ForeignKeyConstraint(['owner'], ['user.id_user'], name='fk_file_folder'),
    sa.PrimaryKeyConstraint('id_file')
    )
    op.create_table('message',
    sa.Column('id_message', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('body', mysql.LONGTEXT(), nullable=True),
    sa.Column('space', sa.Integer(), nullable=True),
    sa.Column('sender', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sender'], ['user.id_user'], name='fk_msg_user'),
    sa.ForeignKeyConstraint(['space'], ['space.id_space'], name='fk_msg_space'),
    sa.PrimaryKeyConstraint('id_message')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message')
    op.drop_table('file')
    op.drop_table('archive')
    op.drop_table('space')
    op.drop_table('folder')
    # ### end Alembic commands ###
